ASP.NET CORE/Hotel Management System Complete/Hotel Management System/Hotel Management System/Controllers/HomeController.cs
using Hotel_Management_System.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace Hotel_Management_System.Controllers
{
    [Authorize]
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }
        
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

ASP.NET CORE/Hotel Management System Complete/Hotel Management System/Hotel Management System/Controllers/RoleController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Hotel_Management_System.Controllers
{
    public class RoleController : Controller
    {
        public IActionResult Home()
        {
            return View();
        }
        [Authorize(Roles = "Owner")]
        public IActionResult Index()
        {
            return View();
        }
        [Authorize(Roles = "Owner,Manager")]
        public IActionResult ManagerIndex()
        {
            return View();
        }
        [Authorize(Roles = "Owner,Receptionist")]
        public IActionResult ReceptionistIndex()
        {
            return View();
        }

    }
}

ASP.NET CORE/Hotel Management System Complete/Hotel Management System/Hotel Management System/Controllers/ServicesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using HMS_Data_Access.HMSModels;
using Microsoft.AspNetCore.Authorization;
using System.Data;

namespace Hotel_Management_System.Controllers
{
    [Authorize(Roles = "Owner,Manager")]
    public class ServicesController : Controller
    {
        private readonly HotelManagementSystemContext _context;

        public ServicesController(HotelManagementSystemContext context)
        {
            _context = context;
        }
        public IActionResult Home()
        {
            return View();
        }
        // GET: Services
        public async Task<IActionResult> Index()
        {
            return View(await _context.Services.ToListAsync());
        }

        // GET: Services/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var services = await _context.Services
                .FirstOrDefaultAsync(m => m.ServiceId == id);
            if (services == null)
            {
                return NotFound();
            }

            return View(services);
        }

        // GET: Services/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Services/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ServiceId,ServiceName,ServicePrice")] Services services)
        {
            if (ModelState.IsValid)
            {
                _context.Add(services);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(services);
        }

        // GET: Services/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var services = await _context.Services.FindAsync(id);
            if (services == null)
            {
                return NotFound();
            }
            return View(services);
        }

        // POST: Services/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ServiceId,ServiceName,ServicePrice")] Services services)
        {
            if (id != services.ServiceId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(services);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ServicesExists(services.ServiceId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(services);
        }

        // GET: Services/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var services = await _context.Services
                .FirstOrDefaultAsync(m => m.ServiceId == id);
            if (services == null)
            {
                return NotFound();
            }

            return View(services);
        }

        // POST: Services/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var services = await _context.Services.FindAsync(id);
            _context.Services.Remove(services);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ServicesExists(int id)
        {
            return _context.Services.Any(e => e.ServiceId == id);
        }
    }
}

ASP.NET CORE/Hotel Management System Complete/Hotel Management System/Hotel Management System/Views/Services/Create.cshtml
@model HMS_Data_Access.HMSModels.Services

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Create</h1>

<h4>Services</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="ServiceId" class="control-label"></label>
                <input asp-for="ServiceId" class="form-control" />
                <span asp-validation-for="ServiceId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ServiceName" class="control-label"></label>
                <input asp-for="ServiceName" class="form-control" />
                <span asp-validation-for="ServiceName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ServicePrice" class="control-label"></label>
                <input asp-for="ServicePrice" class="form-control" />
                <span asp-validation-for="ServicePrice" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
    <a asp-action="Index" asp-controller="Role">HMS Home Page</a>
</div>

ASP.NET CORE/Hotel Management System Complete/Hotel Management System/Hotel Management System/Views/Services/Delete.cshtml
@model HMS_Data_Access.HMSModels.Services

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Services</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ServiceName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ServiceName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ServicePrice)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ServicePrice)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="ServiceId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
        <a asp-action="Index" asp-controller="Role">HMS Home Page</a>
    </form>
</div>

ASP.NET CORE/Hotel Management System Complete/Hotel Management System/Hotel Management System/Views/Services/Details.cshtml
@model HMS_Data_Access.HMSModels.Services

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Details</h1>

<div>
    <h4>Services</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ServiceName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ServiceName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ServicePrice)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ServicePrice)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.ServiceId">Edit</a> |
    <a asp-action="Index">Back to List</a>
    <a asp-action="Index" asp-controller="Role">HMS Home Page</a>
</div>

ASP.NET CORE/Hotel Management System Complete/Hotel Management System/Hotel Management System/Views/Services/Edit.cshtml
@model HMS_Data_Access.HMSModels.Services

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Edit</h1>

<h4>Services</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="ServiceId" />
            <div class="form-group">
                <label asp-for="ServiceName" class="control-label"></label>
                <input asp-for="ServiceName" class="form-control" />
                <span asp-validation-for="ServiceName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ServicePrice" class="control-label"></label>
                <input asp-for="ServicePrice" class="form-control" />
                <span asp-validation-for="ServicePrice" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
    <a asp-action="Index" asp-controller="Role">HMS Home Page</a>
</div>

ASP.NET CORE/Hotel Management System Complete/Hotel Management System/Hotel Management System/Views/Services/Home.cshtml
<h1>Services</h1>
<ul>
    <li><a asp-action="Index" asp-controller="Services">Services</a></li>
    <li><a asp-action="Create" asp-controller="Services">Add a Service</a></li>
    <li><a asp-action="Index" asp-controller="Role">HMS Home Page</a></li>
    <li><a asp-action="ManagerIndex" asp-controller="Role">HMS ManagerHome Page</a></li>
    <li><a asp-action="ReceptionistIndex" asp-controller="Role">HMS ReceptionistHome Page</a></li>
</ul>

ASP.NET CORE/Hotel Management System Complete/Hotel Management System/Hotel Management System/Views/Services/Index.cshtml
@model IEnumerable<HMS_Data_Access.HMSModels.Services>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.ServiceName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ServicePrice)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.ServiceName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ServicePrice)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.ServiceId">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.ServiceId">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.ServiceId">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>