ASP.NET CORE/Hotel Management System Complete/Hotel Management System/Hotel Management System/Controllers/HomeController.cs
using Hotel_Management_System.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace Hotel_Management_System.Controllers
{
    [Authorize]
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }
        
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

ASP.NET CORE/Hotel Management System Complete/Hotel Management System/Hotel Management System/Controllers/RoleController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Hotel_Management_System.Controllers
{
    public class RoleController : Controller
    {
        public IActionResult Home()
        {
            return View();
        }
        [Authorize(Roles = "Owner")]
        public IActionResult Index()
        {
            return View();
        }
        [Authorize(Roles = "Owner,Manager")]
        public IActionResult ManagerIndex()
        {
            return View();
        }
        [Authorize(Roles = "Owner,Receptionist")]
        public IActionResult ReceptionistIndex()
        {
            return View();
        }

    }
}

ASP.NET CORE/Hotel Management System Complete/Hotel Management System/Hotel Management System/Controllers/StaffDetailsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using HMS_Data_Access.HMSModels;
using Microsoft.AspNetCore.Authorization;
using System.Data;

namespace Hotel_Management_System.Controllers
{
    [Authorize(Roles = "Owner,Manager")]
    public class StaffDetailsController : Controller
    {
        private readonly HotelManagementSystemContext _context;

        public StaffDetailsController(HotelManagementSystemContext context)
        {
            _context = context;
        }
        public IActionResult Home()
        {
            return View();
        }
        // GET: StaffDetails
        public async Task<IActionResult> Index()
        {
            var hotelManagementSystemContext = _context.StaffDetails.Include(s => s.Department);
            return View(await hotelManagementSystemContext.ToListAsync());
        }

        // GET: StaffDetails/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var staffDetails = await _context.StaffDetails
                .Include(s => s.Department)
                .FirstOrDefaultAsync(m => m.StaffId == id);
            if (staffDetails == null)
            {
                return NotFound();
            }

            return View(staffDetails);
        }

        // GET: StaffDetails/Create
        public IActionResult Create()
        {
            ViewData["DepartmentId"] = new SelectList(_context.Department, "DepartmentId", "DepartmentId");
            return View();
        }

        // POST: StaffDetails/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("StaffId,StaffName,StaffAddress,Occupation,Email,Age,Salary,Nic,DepartmentId")] StaffDetails staffDetails)
        {
            if (ModelState.IsValid)
            {
                _context.Add(staffDetails);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["DepartmentId"] = new SelectList(_context.Department, "DepartmentId", "DepartmentId", staffDetails.DepartmentId);
            return View(staffDetails);
        }

        // GET: StaffDetails/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var staffDetails = await _context.StaffDetails.FindAsync(id);
            if (staffDetails == null)
            {
                return NotFound();
            }
            ViewData["DepartmentId"] = new SelectList(_context.Department, "DepartmentId", "DepartmentId", staffDetails.DepartmentId);
            return View(staffDetails);
        }

        // POST: StaffDetails/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("StaffId,StaffName,StaffAddress,Occupation,Email,Age,Salary,Nic,DepartmentId")] StaffDetails staffDetails)
        {
            if (id != staffDetails.StaffId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(staffDetails);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!StaffDetailsExists(staffDetails.StaffId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["DepartmentId"] = new SelectList(_context.Department, "DepartmentId", "DepartmentId", staffDetails.DepartmentId);
            return View(staffDetails);
        }

        // GET: StaffDetails/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var staffDetails = await _context.StaffDetails
                .Include(s => s.Department)
                .FirstOrDefaultAsync(m => m.StaffId == id);
            if (staffDetails == null)
            {
                return NotFound();
            }

            return View(staffDetails);
        }

        // POST: StaffDetails/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var staffDetails = await _context.StaffDetails.FindAsync(id);
            _context.StaffDetails.Remove(staffDetails);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool StaffDetailsExists(int id)
        {
            return _context.StaffDetails.Any(e => e.StaffId == id);
        }
    }
}

ASP.NET CORE/Hotel Management System Complete/Hotel Management System/Hotel Management System/Views/StaffDetails/Create.cshtml
@model HMS_Data_Access.HMSModels.StaffDetails

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Create</h1>

<h4>StaffDetails</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="StaffId" class="control-label"></label>
                <input asp-for="StaffId" class="form-control" />
                <span asp-validation-for="StaffId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="StaffName" class="control-label"></label>
                <input asp-for="StaffName" class="form-control" />
                <span asp-validation-for="StaffName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="StaffAddress" class="control-label"></label>
                <input asp-for="StaffAddress" class="form-control" />
                <span asp-validation-for="StaffAddress" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Occupation" class="control-label"></label>
                <input asp-for="Occupation" class="form-control" />
                <span asp-validation-for="Occupation" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Age" class="control-label"></label>
                <input asp-for="Age" class="form-control" />
                <span asp-validation-for="Age" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Salary" class="control-label"></label>
                <input asp-for="Salary" class="form-control" />
                <span asp-validation-for="Salary" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Nic" class="control-label"></label>
                <input asp-for="Nic" class="form-control" />
                <span asp-validation-for="Nic" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DepartmentId" class="control-label"></label>
                <select asp-for="DepartmentId" class ="form-control" asp-items="ViewBag.DepartmentId"></select>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
    <a asp-action="Index" asp-controller="Role">HMS Home Page</a>
</div>

ASP.NET CORE/Hotel Management System Complete/Hotel Management System/Hotel Management System/Views/StaffDetails/Delete.cshtml
@model HMS_Data_Access.HMSModels.StaffDetails

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>StaffDetails</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.StaffName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.StaffName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.StaffAddress)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.StaffAddress)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Occupation)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Occupation)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Age)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Age)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Salary)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Salary)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nic)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nic)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Department)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Department.DepartmentId)
        </dd class>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="StaffId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
        <a asp-action="Index" asp-controller="Role">HMS Home Page</a>
    </form>
</div>

ASP.NET CORE/Hotel Management System Complete/Hotel Management System/Hotel Management System/Views/StaffDetails/Details.cshtml
@model HMS_Data_Access.HMSModels.StaffDetails

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Details</h1>

<div>
    <h4>StaffDetails</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.StaffName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.StaffName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.StaffAddress)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.StaffAddress)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Occupation)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Occupation)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Age)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Age)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Salary)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Salary)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nic)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nic)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Department)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Department.DepartmentId)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.StaffId">Edit</a> |
    <a asp-action="Index">Back to List</a>
    <a asp-action="Index" asp-controller="Role">HMS Home Page</a>
</div>

ASP.NET CORE/Hotel Management System Complete/Hotel Management System/Hotel Management System/Views/StaffDetails/Edit.cshtml
@model HMS_Data_Access.HMSModels.StaffDetails

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Edit</h1>

<h4>StaffDetails</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="StaffId" />
            <div class="form-group">
                <label asp-for="StaffName" class="control-label"></label>
                <input asp-for="StaffName" class="form-control" />
                <span asp-validation-for="StaffName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="StaffAddress" class="control-label"></label>
                <input asp-for="StaffAddress" class="form-control" />
                <span asp-validation-for="StaffAddress" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Occupation" class="control-label"></label>
                <input asp-for="Occupation" class="form-control" />
                <span asp-validation-for="Occupation" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Age" class="control-label"></label>
                <input asp-for="Age" class="form-control" />
                <span asp-validation-for="Age" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Salary" class="control-label"></label>
                <input asp-for="Salary" class="form-control" />
                <span asp-validation-for="Salary" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Nic" class="control-label"></label>
                <input asp-for="Nic" class="form-control" />
                <span asp-validation-for="Nic" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DepartmentId" class="control-label"></label>
                <select asp-for="DepartmentId" class="form-control" asp-items="ViewBag.DepartmentId"></select>
                <span asp-validation-for="DepartmentId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
    <a asp-action="Index" asp-controller="Role">HMS Home Page</a>
</div>

ASP.NET CORE/Hotel Management System Complete/Hotel Management System/Hotel Management System/Views/StaffDetails/Home.cshtml
<h1>Staff Details</h1>
<ul>
    <li><a asp-action="Index" asp-controller="StaffDetails">StaffDetails</a></li>
    <li><a asp-action="Create" asp-controller="StaffDetails">Add a staff member</a></li>
    <li><a asp-action="Index" asp-controller="Role">HMS Home Page</a></li>
    <li><a asp-action="ManagerIndex" asp-controller="Role">HMS ManagerHome Page</a></li>
    <li><a asp-action="ReceptionistIndex" asp-controller="Role">HMS ReceptionistHome Page</a></li>
</ul>

ASP.NET CORE/Hotel Management System Complete/Hotel Management System/Hotel Management System/Views/StaffDetails/Index.cshtml
@model IEnumerable<HMS_Data_Access.HMSModels.StaffDetails>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.StaffName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.StaffAddress)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Occupation)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Email)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Age)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Salary)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Nic)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Department)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.StaffName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.StaffAddress)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Occupation)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Email)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Age)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Salary)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Nic)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Department.DepartmentId)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.StaffId">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.StaffId">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.StaffId">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>
<a asp-action="Index" asp-controller="Role">HMS Home Page</a>