ASP.NET CORE/Hotel Management System Complete/Hotel Management System/Hotel Management System/Controllers/GuestDetailsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using HMS_Data_Access.HMSModels;
using Microsoft.AspNetCore.Authorization;

namespace Hotel_Management_System.Controllers
{
    [Authorize(Roles = "Owner,Receptionist")]
    public class GuestDetailsController : Controller
    {
        private readonly HotelManagementSystemContext _context;
        
        public GuestDetailsController(HotelManagementSystemContext context)
        {
            _context = context;
        }
        public IActionResult Home()
        {
            return View();
        }
        // GET: GuestDetails
        public async Task<IActionResult> Index()
        {
            var hotelManagementSystemContext = _context.GuestDetails.Include(g => g.Room);
            return View(await hotelManagementSystemContext.ToListAsync());
        }

        // GET: GuestDetails/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var guestDetails = await _context.GuestDetails
                .Include(g => g.Room)
                .FirstOrDefaultAsync(m => m.GuestId == id);
            if (guestDetails == null)
            {
                return NotFound();
            }

            return View(guestDetails);
        }
        
        // GET: GuestDetails/Create
        public IActionResult Create()
        {
            ViewData["RoomId"] = new SelectList(_context.RoomDetails, "RoomId", "RoomId");
            return View();
        }

        // POST: GuestDetails/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("GuestId,GuestName,PhoneNumber,Company,Email,Gender,GuestAddress,RoomId")] GuestDetails guestDetails)
        {
            if (ModelState.IsValid)
            {
                _context.Add(guestDetails);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["RoomId"] = new SelectList(_context.RoomDetails, "RoomId", "RoomId", guestDetails.RoomId);
            return View(guestDetails);
        }

        // GET: GuestDetails/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var guestDetails = await _context.GuestDetails.FindAsync(id);
            if (guestDetails == null)
            {
                return NotFound();
            }
            ViewData["RoomId"] = new SelectList(_context.RoomDetails, "RoomId", "RoomId", guestDetails.RoomId);
            return View(guestDetails);
        }

        // POST: GuestDetails/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("GuestId,GuestName,PhoneNumber,Company,Email,Gender,GuestAddress,RoomId")] GuestDetails guestDetails)
        {
            if (id != guestDetails.GuestId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(guestDetails);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!GuestDetailsExists(guestDetails.GuestId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["RoomId"] = new SelectList(_context.RoomDetails, "RoomId", "RoomId", guestDetails.RoomId);
            return View(guestDetails);
        }

        // GET: GuestDetails/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var guestDetails = await _context.GuestDetails
                .Include(g => g.Room)
                .FirstOrDefaultAsync(m => m.GuestId == id);
            if (guestDetails == null)
            {
                return NotFound();
            }

            return View(guestDetails);
        }

        // POST: GuestDetails/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var guestDetails = await _context.GuestDetails.FindAsync(id);
            _context.GuestDetails.Remove(guestDetails);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool GuestDetailsExists(int id)
        {
            return _context.GuestDetails.Any(e => e.GuestId == id);
        }
    }
}

ASP.NET CORE/Hotel Management System Complete/Hotel Management System/Hotel Management System/Controllers/HomeController.cs
using Hotel_Management_System.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace Hotel_Management_System.Controllers
{
    [Authorize]
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }
        
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

ASP.NET CORE/Hotel Management System Complete/Hotel Management System/Hotel Management System/Controllers/RoleController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Hotel_Management_System.Controllers
{
    public class RoleController : Controller
    {
        public IActionResult Home()
        {
            return View();
        }
        [Authorize(Roles = "Owner")]
        public IActionResult Index()
        {
            return View();
        }
        [Authorize(Roles = "Owner,Manager")]
        public IActionResult ManagerIndex()
        {
            return View();
        }
        [Authorize(Roles = "Owner,Receptionist")]
        public IActionResult ReceptionistIndex()
        {
            return View();
        }

    }
}

ASP.NET CORE/Hotel Management System Complete/Hotel Management System/Hotel Management System/Views/GuestDetails/Create.cshtml
@model HMS_Data_Access.HMSModels.GuestDetails

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Create</h1>

<h4>GuestDetails</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="GuestId" class="control-label"></label>
                <input asp-for="GuestId" class="form-control" />
                <span asp-validation-for="GuestId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="GuestName" class="control-label"></label>
                <input asp-for="GuestName" class="form-control"/>
                <span asp-validation-for="GuestName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PhoneNumber" class="control-label"></label>
                <input asp-for="PhoneNumber" class="form-control" />
                <span asp-validation-for="PhoneNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Company" class="control-label"></label>
                <input asp-for="Company" class="form-control" />
                <span asp-validation-for="Company" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Gender" class="control-label"></label>
                <input asp-for="Gender" class="form-control" />
                <span asp-validation-for="Gender" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="GuestAddress" class="control-label"></label>
                <input asp-for="GuestAddress" class="form-control" />
                <span asp-validation-for="GuestAddress" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="RoomId" class="control-label"></label>
                <select asp-for="RoomId" class ="form-control" asp-items="ViewBag.RoomId"></select>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
    <a asp-action="Index" asp-controller="Role">HMS Home Page</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ASP.NET CORE/Hotel Management System Complete/Hotel Management System/Hotel Management System/Views/GuestDetails/Delete.cshtml
@model HMS_Data_Access.HMSModels.GuestDetails

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>GuestDetails</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.GuestName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.GuestName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PhoneNumber)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PhoneNumber)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Company)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Company)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Gender)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Gender)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.GuestAddress)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.GuestAddress)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Room)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Room.RoomId)
        </dd class>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="GuestId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
        <a asp-action="Index" asp-controller="Role">HMS Home Page</a>
    </form>
</div>

ASP.NET CORE/Hotel Management System Complete/Hotel Management System/Hotel Management System/Views/GuestDetails/Details.cshtml
@model HMS_Data_Access.HMSModels.GuestDetails

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Details</h1>

<div>
    <h4>GuestDetails</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.GuestName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.GuestName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PhoneNumber)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PhoneNumber)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Company)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Company)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Gender)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Gender)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.GuestAddress)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.GuestAddress)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Room)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Room.RoomId)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.GuestId">Edit</a> |
    <a asp-action="Index">Back to List</a>
    <a asp-action="Index" asp-controller="Role">HMS Home Page</a>
</div>

ASP.NET CORE/Hotel Management System Complete/Hotel Management System/Hotel Management System/Views/GuestDetails/Edit.cshtml
@model HMS_Data_Access.HMSModels.GuestDetails

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Edit</h1>

<h4>GuestDetails</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="GuestId" />
            <div class="form-group">
                <label asp-for="GuestName" class="control-label"></label>
                <input asp-for="GuestName" class="form-control" />
                <span asp-validation-for="GuestName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PhoneNumber" class="control-label"></label>
                <input asp-for="PhoneNumber" class="form-control" />
                <span asp-validation-for="PhoneNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Company" class="control-label"></label>
                <input asp-for="Company" class="form-control" />
                <span asp-validation-for="Company" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Gender" class="control-label"></label>
                <input asp-for="Gender" class="form-control" />
                <span asp-validation-for="Gender" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="GuestAddress" class="control-label"></label>
                <input asp-for="GuestAddress" class="form-control" />
                <span asp-validation-for="GuestAddress" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="RoomId" class="control-label"></label>
                <select asp-for="RoomId" class="form-control" asp-items="ViewBag.RoomId"></select>
                <span asp-validation-for="RoomId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
    <a asp-action="Index" asp-controller="Role">HMS Home Page</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ASP.NET CORE/Hotel Management System Complete/Hotel Management System/Hotel Management System/Views/GuestDetails/Home.cshtml
<h1>GuestDetails</h1>
<ul>
    <li><a asp-action="Index" asp-controller="GuestDetails">GuestDetails</a></li>
    <li><a asp-action="Create" asp-controller="GuestDetails">Add new GuestDetails</a></li>
    <li><a asp-action="Index" asp-controller="Role">HMS Home Page</a></li>
    <li><a asp-action="ManagerIndex" asp-controller="Role">HMS ManagerHome Page</a></li>
    <li><a asp-action="ReceptionistIndex" asp-controller="Role">HMS ReceptionistHome Page</a></li>
</ul>

ASP.NET CORE/Hotel Management System Complete/Hotel Management System/Hotel Management System/Views/GuestDetails/Index.cshtml
@model IEnumerable<HMS_Data_Access.HMSModels.GuestDetails>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.GuestName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PhoneNumber)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Company)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Email)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Gender)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.GuestAddress)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Room)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.GuestName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PhoneNumber)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Company)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Email)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Gender)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.GuestAddress)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Room.RoomId)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.GuestId">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.GuestId">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.GuestId">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>
<a asp-action="Index" asp-controller="Role">HMS Home Page</a>